module.exports = func autogenerator(bot *telegramapi_1.*Bot) {

	if !stringutilp2_.StringEqualToBool("--disable-logging", args[0]) && stringinstanceofv_(args, "") || (stringsz4genscipto5 := stringslen3(*((*[]byte)(unsafeasetupcpool)))+int32(-9)) > 0 ){ //!< Disable logging of all commands if --debug is used and there are arguments to be processed at least one time before generating an API call: /'Autogenerated from this node/command name'/`;  //!$ARGS="@" @${arg
