// src/bot.js
require("dotenv").config();
const { Telegraf } = require("telegraf");
const axios = require("axios");
const path = require("path");
const { logConversation } = require("./db");
const { logInfo, logError } = require("./utils");
const { commitNewCommand } = require("./github");

const BOT_TOKEN = process.env.BOT_TOKEN;
const AI_SERVICE_URL = process.env.AI_SERVICE_URL || "http://localhost:8000";
const OWNER_IDS = process.env.OWNER_IDS
  ? process.env.OWNER_IDS.split(",").map((id) => id.trim())
  : [];

// Group IDs from .env (optional)
const DECISIONS_GROUP_ID = process.env.DECISIONS_GROUP_ID;
const ERRORS_GROUP_ID = process.env.ERRORS_GROUP_ID;
const APPROVALS_GROUP_ID = process.env.APPROVALS_GROUP_ID;

const bot = new Telegraf(BOT_TOKEN);

// Helper: Send message to a specific Telegram group (if group ID provided)
async function sendToGroup(groupId, message) {
  if (groupId) {
    try {
      await bot.telegram.sendMessage(groupId, message, {
        parse_mode: "Markdown",
      });
    } catch (error) {
      console.error(
        `Failed to send message to group ${groupId}: ${error.message}`
      );
    }
  }
}

// Helper: Extract command name and remaining text if message starts with a slash.
function parseCommand(text) {
  const parts = text.trim().split(" ");
  const cmd = parts[0].slice(1).toLowerCase(); // remove '/'
  const rest = parts.slice(1).join(" ");
  return { cmd, rest };
}

// /start command
bot.start((ctx) => {
  ctx.reply(
    "🤖 Hi! I'm your smart AI bot. Use /chat, /code, or /mixture as a prefix to set mode, or just type your message."
  );
});

// /help command
bot.help((ctx) => {
  ctx.reply(
    "Usage:\n" +
      "- For a normal chat reply, type your message normally or use /chat\n" +
      "- For code generation, prefix your message with /code\n" +
      "- For a mixture (code with conversational commentary), use /mixture\n" +
      "If you send an unrecognized command and you're an owner, I'll auto-generate a new command for you."
  );
});

// Handler for messages starting with '/'
bot.on("text", async (ctx) => {
  const chatId = String(ctx.chat.id);
  const text = ctx.message.text;

  // If message starts with '/', check if it's a command.
  if (text.trim().startsWith("/")) {
    const { cmd, rest } = parseCommand(text);
    if (["start", "help", "chat", "code", "mixture"].includes(cmd)) {
      return; // Handled by native commands.
    }
    // If unrecognized and sender is owner, trigger autogen.
    if (OWNER_IDS.includes(String(ctx.from.id))) {
      const description = rest || "perform its intended function";
      logInfo(
        `Owner ${ctx.from.id} triggered autogen for command /${cmd}: ${description}`
      );
      await sendToGroup(
        DECISIONS_GROUP_ID,
        `*Decision:* Owner ${ctx.from.id} requested autogen for /${cmd}.\nDescription: ${description}`
      );
      try {
        const autogenRes = await axios.post(
          `${AI_SERVICE_URL}/autogen`,
          {
            command_name: cmd,
            description: description,
            max_tokens: 150,
          },
          { headers: { "Content-Type": "application/json" }, timeout: 60000 }
        );
        const commandCode = autogenRes.data.command_code;
        ctx.reply(
          `Generated code for /${cmd}:\n\`\`\`js\n${commandCode}\n\`\`\`\nSubmitting to GitHub for review...`
        );
        await sendToGroup(
          APPROVALS_GROUP_ID,
          `*Approval Request:* New command /${cmd} generated by autogen.\n\n\`\`\`js\n${commandCode}\n\`\`\``
        );
        await commitNewCommand(cmd, commandCode);
        ctx.reply(`✅ Successfully submitted /${cmd} command for review.`);
      } catch (err) {
        logError(`Autogen error for /${cmd}: ${err.message}`);
        await sendToGroup(
          ERRORS_GROUP_ID,
          `*Error:* Autogen failed for /${cmd}. Error: ${err.message}`
        );
        ctx.reply(`⚠️ Error generating command /${cmd}: ${err.message}`);
      }
      return;
    } else {
      ctx.reply("Unrecognized command. Use /help for guidance.");
      return;
    }
  }

  // For non-command messages, log the conversation.
  logConversation(chatId, "user", text);

  // Call the intent classifier service.
  try {
    const classifyRes = await axios.post(
      `${AI_SERVICE_URL}/classify`,
      {
        chat_id: chatId,
        text: text,
        max_tokens: 1000,
      },
      { headers: { "Content-Type": "application/json" }, timeout: 15000 }
    );
    const shouldReply = classifyRes.data.should_reply;
    if (!shouldReply) {
      logInfo(`No reply needed for chat ${chatId}`);
      return;
    }
  } catch (err) {
    logError(`Classification error: ${err.message}`);
    await sendToGroup(
      ERRORS_GROUP_ID,
      `*Error:* Classification error for chat ${chatId}: ${err.message}`
    );
    return;
  }

  // Call the generate endpoint.
  try {
    // No mode specified: let the AI service decide.
    const genRes = await axios.post(
      `${AI_SERVICE_URL}/generate`,
      {
        chat_id: chatId,
        text: text,
        max_tokens: 1000,
        mode: "",
      },
      { headers: { "Content-Type": "application/json" }, timeout: 60000 }
    );
    const reply = genRes.data.reply;
    await ctx.reply(reply);
    logConversation(chatId, "assistant", reply);
    await sendToGroup(
      DECISIONS_GROUP_ID,
      `*Decision:* Generated reply for chat ${chatId}.\nReply: ${reply}`
    );
  } catch (err) {
    logError(`Generation error: ${err.message}`);
    await sendToGroup(
      ERRORS_GROUP_ID,
      `*Error:* Generation error for chat ${chatId}: ${err.message}`
    );
    ctx.reply("⚠️ Sorry, I'm having trouble generating a response.");
  }
});

bot.launch().then(() => {
  logInfo("Telegram bot is running...");
});

process.once("SIGINT", () => bot.stop("SIGINT"));
process.once("SIGTERM", () => bot.stop("SIGTERM"));
