// src/github.js
const { Octokit } = require("@octokit/rest");
require("dotenv").config();

const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
const OWNER = process.env.GITHUB_REPO_OWNER;
const REPO = process.env.GITHUB_REPO_NAME;
const MAIN_BRANCH = process.env.GITHUB_MAIN_BRANCH || "staging";

async function commitNewCommand(cmdName, code) {
  try {
    const { data: baseRef } = await octokit.git.getRef({
      owner: OWNER,
      repo: REPO,
      ref: `heads/${MAIN_BRANCH}`,
    });
    const baseSha = baseRef.object.sha;

    const branchName = `auto/${cmdName}-${Date.now()}`;
    await octokit.git.createRef({
      owner: OWNER,
      repo: REPO,
      ref: `refs/heads/${branchName}`,
      sha: baseSha,
    });

    const filePath = `src/commands/${cmdName}.js`;
    const fileContent = `module.exports = ${code.trim()}\n`;
    const contentEncoded = Buffer.from(fileContent, "utf8").toString("base64");

    await octokit.repos.createOrUpdateFileContents({
      owner: OWNER,
      repo: REPO,
      path: filePath,
      branch: branchName,
      message: `Add /${cmdName} command (AI-generated)`,
      content: contentEncoded,
    });

    const pr = await octokit.pulls.create({
      owner: OWNER,
      repo: REPO,
      head: branchName,
      base: MAIN_BRANCH,
      title: `Add /${cmdName} command (AI-generated)`,
      body: `This PR adds the /${cmdName} command generated by the AI bot.`,
    });

    console.log(`GitHub: Created PR #${pr.data.number} for /${cmdName}`);
    return pr.data;
  } catch (err) {
    console.error("GitHub integration error:", err);
    throw err;
  }
}

module.exports = { commitNewCommand };
