// src/github.js
require("dotenv").config();

async function getOctokit() {
  // Dynamically import Octokit from the ESM package
  const { Octokit } = await import("@octokit/rest");
  return new Octokit({ auth: process.env.GITHUB_TOKEN });
}

const OWNER = process.env.GITHUB_REPO_OWNER;
const REPO = process.env.GITHUB_REPO_NAME;
const MAIN_BRANCH = process.env.GITHUB_MAIN_BRANCH || "staging";

async function commitNewCommand(cmdName, code) {
  try {
    const octokit = await getOctokit();
    // Get the latest commit SHA from the staging branch.
    const { data: baseRef } = await octokit.git.getRef({
      owner: OWNER,
      repo: REPO,
      ref: `heads/${MAIN_BRANCH}`,
    });
    const baseSha = baseRef.object.sha;

    // Create a new branch.
    const branchName = `auto/${cmdName}-${Date.now()}`;
    await octokit.git.createRef({
      owner: OWNER,
      repo: REPO,
      ref: `refs/heads/${branchName}`,
      sha: baseSha,
    });

    // Create the new command file content.
    const filePath = `src/commands/${cmdName}.js`;
    const fileContent = `module.exports = ${code.trim()}\n`;
    const contentEncoded = Buffer.from(fileContent, "utf8").toString("base64");

    // Create or update the file in the new branch.
    await octokit.repos.createOrUpdateFileContents({
      owner: OWNER,
      repo: REPO,
      path: filePath,
      branch: branchName,
      message: `Add /${cmdName} command (AI-generated)`,
      content: contentEncoded,
    });

    // Create a pull request from the new branch into staging.
    const pr = await octokit.pulls.create({
      owner: OWNER,
      repo: REPO,
      head: branchName,
      base: MAIN_BRANCH,
      title: `Add /${cmdName} command (AI-generated)`,
      body: `This PR adds the /${cmdName} command generated by the AI bot.`,
    });

    console.log(`GitHub: Created PR #${pr.data.number} for /${cmdName}`);
    return pr.data;
  } catch (err) {
    console.error("GitHub integration error:", err.message);
    throw err;
  }
}

module.exports = { commitNewCommand };
